### ISSUE TITLE
Usage Instructions?  Expectations?  "No eligible build target."

### ISSUE THREAD

**Issue by ghost** [AtomBuild/atom-build-cargo#13]
I guess it's just supposed to work?  But it isn't just working for me so i'm stuck at the moment.  I assume I have to figure out how add a build definition, but I don't know how to do that for atom-build nor for cargo-build.

> No eligible build target.
> No configuration to build this project exists.

![image](https://cloud.githubusercontent.com/assets/5518652/11429018/ed536a9e-943f-11e5-8413-17476fc402b3.png)

**Comment by noseglid** [comment]
If you issue `Build: refresh targets` via the command palette. Does it work then?

`build-cargo` should react if `Cargo.toml` exists and provide build targets for you, so your setup seems correct.

**Comment by colin-kiegel** [comment]
Or try to disable other Plugins. I had to disable linter-php to make atom-buil-cargo work

**Comment by ghost** [comment]
I'm not sure what worked.  Quitting Atom and starting it again wasn't effective, but logging out and in again worked.  I had previously uninstalled and reinstalled both atom-build and cargo-build prior to the restart of the session.  Thanks though.

**Comment by noseglid** [comment]
Good it's working. I'll close this out. Please re-open if you have more information.

**Comment by ghost** [comment]
`Build: refresh targets` worked here. Would you please add this to a README, because this did not get set up correctly for me? :/

**Comment by msheke101** [comment]
Hi @noseglid im facing the same 

problem ligible build target.: No configuration to build this project exists.
at file:///C:/Users/mnkabinde/.atom/packages/build/lib/build.js:113:15

could you kindly assist 
![error](https://user-images.githubusercontent.com/32699346/35807341-236777a6-0a8b-11e8-9517-2101013ccd33.jpg)

**Comment by rabbitoc** [comment]
Hi @msheke101  were you able to solve the problem of "no eligible build target"?
