### ISSUE TITLE
"No targets found." when executing "build: Select Active Target"

### ISSUE THREAD

**Issue by yasuyuki** [AtomBuild/atom-build-cargo#15]
I newly installed build and build-cargo, then restart Atom.
I opened command palette and execute "build: Select Active Target". but it displays "No targets found."
"build: Refresh Targets" doesn't cause any effects.

Atom 1.3.1
build 0.50.0
build-cargo 0.10.0
other plugins are disabled.

Similar problem is discussed at build plugin.
https://github.com/noseglid/atom-build/issues/230

**Comment by noseglid** [comment]
Could you include a screenshot of atom (the tree-view in particular)?

**Comment by noseglid** [comment]
Closing due to no response. Please re-open the issue if the problem persists.
