### ISSUE TITLE
Plugin doesn't work with build-cargo

### ISSUE THREAD

**Issue by noseglid** [AtomBuild/atom-build-cargo#20]
Copied from noseglid/atom-build#308 from @Pzixel

> I have atom-build and build-cargo packages enabled, but when I use build command it shows an error
> 
> > No configuration to build this project exists.
> 
> I readed documentation multiple times and got that it seems that plugin should automaticly link with build-cargo and doesn't require any custom configuration, because there is nothing about it on project's main page. But it shows that configuration is not set. Both plugins are enabled and should work fine.
> 
> There is two possibilites: it could be a bug or it could be a documentation absence.
> Unfortunly, I cannot provide any additional information, because I have clean installed new version of atom and every plugin (I have language-rust or racer additionaly installed only). Of course, I can provide any logs if required and if they are stored somewhere.

**Comment by noseglid** [comment]
There has to be a file named `Cargo.toml` in your project root. Can you verify that this is the case?

**Comment by Pzixel** [comment]
I created a project with `cargo new` command so it isn't, the file structure is fine.

**Comment by noseglid** [comment]
Create one, does it work then?

**Comment by Pzixel** [comment]
No, it doesn't. See screenshot
![2016-02-01 1](https://cloud.githubusercontent.com/assets/11201122/12726608/966c1b80-c929-11e5-9507-fd7fea59ffb3.png)

**Comment by noseglid** [comment]
It is not in your project root. You need to open `test_git` so it is your project root.

**Comment by Pzixel** [comment]
Oh, i got it. Now it's highlighted as green and works. Well, it could be closed, I will create another feature request, thank you for help. I didn't expect that folder level cause plugin to stop working.
