### ISSUE TITLE
[Feature request] Cargo run

### ISSUE THREAD

**Issue by Pzixel** [AtomBuild/atom-build-cargo#22]
Please, add possibility to run a program from your plugin. I has output for errors so it can be used as stdio for console application.

I have to found similar issue in closed requests, but it's closed with `okay, I found a solution`. But I didn't find any correlated option in build.

**Comment by Pzixel** [comment]
I found `Cargo: Run` in `cargo.js` module, but it doesn't appear in Atom `ctrl+shift+P` doesn't contain anything about it, just `Build: Stop`, `Build:Confirm` and so on. And there is no commands with `Cargo` prefix.

**Comment by noseglid** [comment]
As you noticed run is supported. You bring up the available targets by pressing `ctrl-alt-t` (`cmd-alt-t` on Mac). Then select `Cargo: Run`.
