### ISSUE TITLE
spaces in path to cargo

### ISSUE THREAD

**Issue by Alexey-Ivanensky** [AtomBuild/atom-build-cargo#23]
`cmd` cannot contain space. Use `args` for arguments.

**Comment by noseglid** [comment]
So what's being executed?
Do you have a modified `cargoPath` ?

**Comment by Alexey-Ivanensky** [comment]
I am on windows and set path to program files dir with rust installed. It tries to execute "C:\Program Files..." and says that it cannot contain spaces. Workaround with short path for now.
What is `cargoPath`?

**Comment by noseglid** [comment]
Did you set this in the settings of the `build-cargo` package? If so, can you try quoting: e.g. "C:\Program Files...".
I don't know if it will work, but worth a shot :)

**Comment by Alexey-Ivanensky** [comment]
Yes, i tried it with quotes and without. It don't work even with quotes, which is strange.

**Comment by noseglid** [comment]
I see. I'm not on windows so it will be difficult for me to help you further. Best advice I can give you is to [create a custom build configuration](https://github.com/noseglid/atom-build#specifying-a-custom-build-command) and try different approaches with quoting. In essence whatever you type in `cmd` is passed to [child_process.spawn of node](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options): https://github.com/noseglid/atom-build/blob/master/lib/build.js#L349

**Comment by Alexey-Ivanensky** [comment]
found this: https://github.com/nodejs/node-v0.x-archive/issues/25895
Error message is clearly wrong - it node.js problem that it doesn't do correct deserialization and passes command to OS incorrectly (it works if no arguments with spaces)

**Comment by noseglid** [comment]
This is fixed in noseglid/atom-build#325 and available in latest build (`v0.55.0`).

**Comment by wy193777** [comment]
Today I encountered this problem again. My path is "C:\Program Files\Rust stable GNU 1.8\bin\cargo.exe". And cargo build says
`Unable to execute: C:\Program Files\Rust stable GNU 1.8\bin\cargo.exe
`cmd` cannot contain space. Use `args` for arguments.
Make sure cmd:'C:\Program Files\Rust stable GNU 1.8\bin\cargo.exe' and cwd:'C:\Users\Shenghan\Dropbox\Rustls\learn' exists and have correct access permissions.
Binaries are found in these folders:.;undefined`

**Comment by wy193777** [comment]
Solved after restart my computer.....

**Comment by wy193777** [comment]
This problem will happen again after succeed cargo build several times from Atom in my computer.

**Comment by noseglid** [comment]
Open a new issue if you're having problems. Please include as much information as possible if I should have any chance of helping you.
