### ISSUE TITLE
rustc can produce errors in json format for easy machine processing

### ISSUE THREAD

**Issue by oli-obk** [AtomBuild/atom-build-cargo#26]
This can be enabled by setting the environment variable `RUSTFLAGS` to `-Zunstable-options --error-format=json`.

@noseglid what do you think about adding a "generate_matches" callback to the settings structure that takes the captured stdout string as an argument and produces match-structs? This would neatly allow this feature to be implemented.

**Comment by noseglid** [comment]
Maybe `errorMatch` could be a function optionally, which receives stdout and stderr and should return match errors. Not a bad idea.

It could also be useful with the `.atom-build.js`, where functions can be defined.

**Comment by noseglid** [comment]
This was fixed by #29
