### ISSUE TITLE
Maintainer wanted!

### ISSUE THREAD

**Issue by noseglid** [AtomBuild/atom-build-cargo#30]
I am currently the primary maintainer of this project. The reason for that is because the cargo support was in `atom-build` before build providers existed. When I moved all of that functionality out to providers I also became the maintainer.

I don't work with `Cargo` or `Rust` on a daily basis and are therefore a quite poor maintainer of this package. I would love to see someone else step in and take over the primary maintenance role. I will still be around for any questions regarding the provider integration, or general administrative task.

Any takers? Please reply here!

**Comment by noseglid** [comment]
@oli-obk @colin-kiegel Any of you interested? Since you seem to be using this I'm sure you'd make a better maintainer than me :)

**Comment by oli-obk** [comment]
sgtm

**Comment by noseglid** [comment]
Awesome @oli-obk ! I've added you as an admin to the project so you should have all permissions!
If you'd like, please join the `atomio` slack channel and I'll invite you to the build-dev channel where we discuss various build related topics!

**Comment by oli-obk** [comment]
I'm not sure how to join that channel, as it requires an `@github.com` address for registration

**Comment by noseglid** [comment]
Hmm, I'm registered with my `@gmail.com` address. Have you tried it?

**Comment by oli-obk** [comment]
that's not available in the dropdown box: https://atomio.slack.com/signup

**Comment by oli-obk** [comment]
> Don't have an @github.com, @fb.com, @adobe.com, @microsoft.com or @jibo.com email address?
> Contact your Team Administrator for an invitation. 

maybe someone can invite me?

`atom6499178473146879941@oli-obk.de`

**Comment by noseglid** [comment]
It's funny, I can't remember how I go my account. I'm unable to find an invite button though..
