### ISSUE TITLE
'cmd' cannot contain spaces on Windows 10

### ISSUE THREAD

**Issue by wy193777** [AtomBuild/atom-build-cargo#31]
Here is error message: 

```
C:\Program Files\Rust stable GNU 1.8\bin\cargo.exe build
Unable to execute: C:\Program Files\Rust stable GNU 1.8\bin\cargo.exe
`cmd` cannot contain space. Use `args` for arguments.
Make sure cmd:'C:\Program Files\Rust stable GNU 1.8\bin\cargo.exe' and cwd:'C:\Users\Shenghan\Dropbox\Rust\ls' exists and have correct access permissions.
Binaries are found in these folders: .;.;undefined
```

If I use default path, the error message is:

```
Unable to execute: cargo
Make sure cmd:'cargo' and cwd:'C:\Users\Shenghan\Dropbox\Rust\ls' exists and have correct access permissions.
Binaries are found in these folders: .;undefined
```

Atom is running as administrator. 
Rust's bin folder has been added to path and I could run cargo `build inside` power shell.

**Comment by noseglid** [comment]
It seems as the PATH is not setup properly. It just says `.` and `undefined`. You're probably not having the same PATH when starting Atom as you have when you're starting power shell. Could you look into this?

**Comment by wy193777** [comment]
Today I reinstalled cargo-build and it worked. I also added cargo to user's PATH. But it works even if I delete cargo from user path.

**Comment by noseglid** [comment]
It seems as the path is setup correctly now then, possibly from some other source.
