### ISSUE TITLE
Warnings support

### ISSUE THREAD

**Issue by alygin** [AtomBuild/atom-build-cargo#37]
Since Atom Build supports not only `errorMatch` but also `warningMatch`, it would be great to use this option and separate warnings from errors. That would be much more convenient than what we have now and result in better user experience.

As far as I understand it would be sufficient to:
1. Rename `matchRelaxed` to `matchError`.
2. Add `matchWarning` that would be a copy of `matchError` except for the part `error:` that must be replaced with `warning:`.
3. Add option `warningMatch: matchWarning` to commands that use `errorMatch`.
4. Replace `matchStrict` with `matchError` whenever it is used now.

I could easily do that but I'm not sure about `matchStrict`. Was it added to only support warnings or for something else? So, does point 4 sound reasonable?

Am I missing something else?

**Comment by oli-obk** [comment]
The idea of `matchStrict` is to deny any output from rustc that has a line/col span attached to it. This way we even error on `note` and `help` level messages when building in release mode. I think the motivation was to not break the build when getting warnings during development.

Point 4 would break this behaviour, so without a good reason I'd rather not do that.

Imo `warningMatch` should be `matchStrict` but only if it's not `error` (can regex do inverted matching?)

**Comment by alygin** [comment]
I can write a universal regex expression that matches all but errors in the Rust output, but unfortunately, it doesn't fit groups that are expected by Atom Build. But since [we know exactly](https://github.com/rust-lang/rust/blob/master/src/doc/rustc-ux-guidelines.md) what types of messages Rust compiler produces, it's safe to just enumerate them in regex.

If someone can come up with a regex that works without enumeration and fits the Atom Build expectations regarding groups, please share it. Otherwise, I suggest the following:
1. Rename `matchRelaxed` to `matchError` and use it everywhere as the `errorMatch` value.
2. Add `matchWarning` that handles markers `warning:`, `note:` and `help:` and use it in commands as the value of `warningMatch`.
3. Remove `matchStrict`.

As the result, real errors will be shown as errors, but warnings, notes and help's as warnings. If you want to preserve everything-is-an-error approach for the release mode, `matchStrict` can be saved and used as the `matchError` for release builds, but at least for me it doesn't seem reasonable and must be optional.

There's a risk that sooner or later Rust will start emitting new types of messages but it can be quickly noticed and fixed.

What do you think?

**Comment by oli-obk** [comment]
Let's go with it. If someone misses the previous behaviour, they can open an issue.

Once json errors become more stable, we should be moving to them permanently anyway and all these troubles would go away.
