### ISSUE TITLE
File link is invalid when points to the Rust core

### ISSUE THREAD

**Issue by alygin** [AtomBuild/atom-build-cargo#41]
If panic is triggered by the Rust core or a standard library, the link to the source code in the error message is broken because it must be applied to the Rust source folder, but Atom Build applies it to our project folder.

The first thought is to analyse the presence of the `RUST_SRC_PATH` environment variable and combine it with the file path emitted by rustc in its error message. The indicator for the necessity of such modification is that the file name starts with '..'  I've got a working prototype, albeit more research must be done on the issue especially when multirust is used.

Unfortunately, Atom Build doesn't allow to omit the file link in the high-level messages, so if the environment variable is not set, we still have to produce the broken link.

Any thoughts?

**Comment by oli-obk** [comment]
have you checked whether cargo path dependencies don't end up introducing `../` paths?

We could replace all unfollowable paths by the first followable one in the trace

**Comment by alygin** [comment]
Good point about cargo path dependencies. I'll check that, though I already switched to using `../src/` or `..\src\` as the indicators.

The problem is that such paths only pop up when a program panics (at least I never met them in other circumstances). As far as I can tell, they cannot be produced by rustc, so we have no additional information rather than a stack trace.

**Comment by alygin** [comment]
It works with path dependencies. When we compile an outer crate that depends on some nested crate, no such problem exist because all the compiled files sit somewhere in our project directory. When vice versa, cargo uses absolute paths instead of relative.

**Comment by alygin** [comment]
Please, check out the PR. It works at least not worse when a user has no env variable and fixes the problem when he or she does. I tried various approaches to handling the case when I can't fix the path, but nothing works good enough to change the default behaviour.
