### ISSUE TITLE
Should support multi-crate projects and cargo workspaces

### ISSUE THREAD

**Issue by pzol** [AtomBuild/atom-build-cargo#44]
If you have project (workspace) directory which has multiple crates in it, the build should be run in the crate dir that contains the Cargo.toml, not the root workspace directory

**Comment by oli-obk** [comment]
I think this is an `atom-build` issue, not a `atom-build-cargo` one.

I don't have much on an opinion, I personally open a new atom instance for every sub project I'm currently working on.

@noseglid what do you think?

**Comment by pzol** [comment]
The issue is, that you need to change the working directory to the closes
Cargo.toml

On Mon, Jul 11, 2016 at 6:33 AM, Oliver Schneider notifications@github.com
wrote:

> I think this is an atom-build issue, not a atom-build-cargo one.
> 
> I don't have much on an opinion, I personally open a new atom instance for
> every sub project I'm currently working on.
> 
> @noseglid https://github.com/noseglid what do you think?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/AtomBuild/atom-build-cargo/issues/44#issuecomment-231735135,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAI2z6WhFBbjsgop0LDt5m5SL-rxhsxiks5qUkYlgaJpZM4JI2qi
> .

## 

Piotr Zolnierek

**Comment by alygin** [comment]
I'm not sure if it will work, but according to the `atom-build`'s API documentation, `preBuild()` method can be used to change `cwd` (which is the working directory for the build command) before the build execution. I think @noseglid could shed some light on it.

**Comment by pzol** [comment]
Actually changing the working dir to the current file's dir does the trick. Cargo figures out the rest

Piotr

**Comment by alygin** [comment]
I've drafted a working prototype that substitutes `cwd` for the build command to the closest (relatively to the active file) directory with `Cargo.toml` in it. It seems to be enough to handle cargo workspaces. At least, it works for my workspace.

So, if nobody disagrees, I could finish it up.
