### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by colin-kiegel** [AtomBuild/atom-build-cargo#53]
I have noticed a lot of very interesting new features were included in the last weeks. What about a new release? :-)

The last version was packaged on May 5th.

**Comment by alygin** [comment]
Vote up. There are some upcoming changes in Rust's error messages and it would be great to have some feedback on recently added features before we have to adapt them to the new format.

**Comment by oli-obk** [comment]
@noseglid can you publish a version and/or give me publish rights?

**Comment by noseglid** [comment]
Hmm, I think you should have rights. Have you tried publishing?

**Comment by alygin** [comment]
Any chance of the release being published by someone? :)

**Comment by oli-obk** [comment]
Sorry, I'm not on a pc until the weekend. I'll do it asap

**Comment by noseglid** [comment]
I've published `v0.16.0`. Let's have a closer look at the permissions next time.

**Comment by alygin** [comment]
Thanks!
