### ISSUE TITLE
Compact backtrace format

### ISSUE THREAD

**Issue by alygin** [AtomBuild/atom-build-cargo#54]
Stack backtraces is a very useful tool for finding and fixing problems in our programs. But some data they contain seems excessive for most use cases when a developer just needs to know the sequence of the function calls. By such excessive data I mean function's addresses and hash codes (or whatever it is at the end of the function name).

It's not a problem per se, but it becomes a bit annoying when displayed in a narrow Atom's notification window. A typical backtrace looks like this on my laptop:

<img width="457" alt="screen shot 2016-08-06 at 07 59 27" src="https://cloud.githubusercontent.com/assets/2101250/17455054/6ba9725c-5bb5-11e6-9078-32c76c75c1f3.png">

What I suggest to do is:
1. Instead of the existing 'Show backtrace information' flag add 'Backtrace' combobox with three options: 'No' (the default one), 'Compact' and 'Full'.
2. 'No' and 'Full' will have the same effect as switching off or on the 'Show backtrace information' flag respectively.
3. 'Compact' will remove addresses and hashes from the backtrace before displaying it to the user. The information on the source code positions will be preserved, of course.

So, the compact form of the same backtrace will be:

<img width="457" alt="screen shot 2016-08-06 at 09 30 05" src="https://cloud.githubusercontent.com/assets/2101250/17455182/66806ecc-5bb8-11e6-8dfc-7fe16ee2eb16.png">

Which is less noisy and easier to grasp at a glance.

What do you think? Am I the only one who forces my brain to ignore all those addresses and hashes most of the time (actually, always) when reading a backtrace?

**Comment by oli-obk** [comment]
fixed in #55
