### ISSUE TITLE
Support for new error format in Rust 1.12

### ISSUE THREAD

**Issue by ancwrd1** [AtomBuild/atom-build-cargo#66]
Because the error format was changed in just released Rust 1.12 the build-cargo doesn't recognize it.

**Comment by alygin** [comment]
There's an existing PR #63 aiming to support the new format.

**Comment by itpetey** [comment]
I've updated to 0.19 but still not getting any feedback from build-cargo since updating Rust to 1.12. Is there a cache I need to clear or something?

**Comment by alygin** [comment]
No cache cleaning is needed. I would only try to restart Atom in such case.
What do you mean by not getting any feedback? What error format do you use: json or human-readable? Do you see the compiler output?

**Comment by ancwrd1** [comment]
For me it worked after restarting Atom.

**Comment by itpetey** [comment]
Sorry - I mean that no issues are reported and seemingly nothing happens. I don't normally see compiler output so I'm not sure how to check that?

I had it set to JSON, but just tried human readable and still didn't have any issues reported.

**Comment by alygin** [comment]
Please, try to switch the Atom Build's output window on. To do that, go to Settings -> Packages -> build -> Settings and set Panel Visibility = Keep Visible. Then try to add some error to your code and build it. Do you see the compiler output?

**Comment by itpetey** [comment]
Ok, this might seem stupid, but the `build` package wasn't installed. How has this ever worked?? I installed build and now all is well. Before updating to Rust 1.12, I got errors being reported so it must have been by `language-rust`? I am so confused.

**Comment by alygin** [comment]
As far as I know, language-rust doesn't report errors, it provides the syntax highlighting and code snippets. But actually, I recently had the same problem -- my `build` package just disappeared and I had to reinstall it. That time, I thought I just accidentally had uninstalled. But since others also experience the same problem, maybe there's some bug in Atom.

**Comment by itpetey** [comment]
Huh...weird. Oh well, thanks very much for the help mate! Really appreciate it.

**Comment by alygin** [comment]
It looks like the problem has been solved and the issue can be closed.
