### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by fschutt** [AtomBuild/atom-build-cargo#82]
I'm sorry to ask this question - but there is no documentation on how to use this plugin. Do I have to enter a command, initiate a keyboard shortcut, right-click somewhere?

I would like to use this plugin, but there's no documentation on how to set it up correctly.

I set up a new project using `cargo new testRust --bin`. Now I want to build it from inside Atom. How?

**Comment by loloof64** [comment]
You can use the plugin options through the menu Packages -> Build.

**Comment by fschutt** [comment]
I found the issue. First of all (this isn't documented anywhere) - your folder containing the Cargo.toml must be the project folder. You have hit Ctrl + Alt + B to build. If the project folder does not contain a Cargo.toml, you'll get errors like "No configuration file found". This was where I was stuck.

Second, you need to restart Atom after installing.

Third, the button to build is in the lower left corner in atom. I overlooked it the first time. 

The issue is resolved now, but I would add the first paragraph to the README.

**Comment by loloof64** [comment]
(Oh, just a fact : I'm just a user of the plugin, not the author :smile: )

**Comment by alygin** [comment]
@sharazam, atom-build-cargo is a build provider for the Atom Build plugin. You can find some useful information on how to build projects and work with linter in [its documentation](https://github.com/noseglid/atom-build#atom-build-package).
