### ISSUE TITLE
Feature: cargo build --release

### ISSUE THREAD

**Issue by HenryTheCat** [AtomBuild/atom-build-cargo#9]
As a Atom and Rust user, I often need to use `cargo build` with option `--release`, but this doesn't seem to be possible at the moment. That would be a nice feature.

**Comment by ebkalderon** [comment]
I agree with this suggestion. :+1:  from me.

**Comment by colin-kiegel** [comment]
You could send a pull request for this file:
https://github.com/noseglid/atom-build-cargo/blob/master/lib/cargo.js

Ideally you would first test it locally of course. It's not very complicated.

**Comment by ebkalderon** [comment]
For reference, see pull request #11.

**Comment by noseglid** [comment]
Fixed with #11

**Comment by HenryTheCat** [comment]
Thanks for satisfying my request and congratulation for the quick resolution! Great job everyone! :)
